In [ ]:
import numpy as np
from sklearn.metrics import mean_squared_error

y = np.array([1, 2, 3])
y_pred = np.array([1, 6, 3])

def mse(data, dataNew):
    return np.sum((data - dataNew)**2) / len(data)

mse(y, y_pred), mean_squared_error(y, y_pred)

(5.333333333333333, 5.333333333333333)

In [ ]:
birds_path = "birds.csv"
with open(birds_path, "r") as f:
    next(f)
    data = np.array([[float(x) for x in line.split(",")] for line in f])

data = data[:5]
data

array([[1020.,   94.],
       [1050.,   93.],
       [4050.,  165.],
       [1567.,  116.],
       [3310.,  165.]])

In [ ]:
# numpy pieces - working with axes
data = np.array(data[:5])
mean = np.mean(data)
mean_axis_0 = np.mean(data, axis=0)
mean_axis_1 = np.mean(data, axis=1)

print('Original data', data, data.shape)
print('Np mean', mean, mean.shape)
print('Np mean, axis=0', mean_axis_0, mean_axis_0.shape)
print('Np mean, axis=1', mean_axis_1, mean_axis_1.shape)

Original data [[1020.   94.]
 [1050.   93.]
 [4050.  165.]
 [1567.  116.]
 [3310.  165.]] (5, 2)
Np mean 1163.0 ()
Np mean, axis=0 [2199.4  126.6] (2,)
Np mean, axis=1 [ 557.   571.5 2107.5  841.5 1737.5] (5,)


In [ ]:
# Standartization and normalization
from sklearn.preprocessing import StandardScaler, normalize as sk_norm

def standartize(data):
    return (data - np.mean(data, axis=0)) / np.std(data, axis=0)

def normalize(data):
    return data / np.linalg.norm(data, axis=0)

# print(StandardScaler().fit(data).transform(data))
# print()
# print(standartize(data))
# print()
print(normalize(data))
print()
print(sk_norm(data, axis=0))
print()
# print(np.linalg.norm(normalize(data), axis=0))
# print()
# print(np.linalg.norm(standartize(data), axis=0))
# print()
# print(np.std(standartize(data), axis=0), np.mean(standartize(data), axis=0))
# print()
# print(np.std(normalize(data), axis=0), np.mean(normalize(data), axis=0))

[[0.18043353 0.32167833]
 [0.1857404  0.31825622]
 [0.71642725 0.56464813]
 [0.27719543 0.39696475]
 [0.58552449 0.56464813]]

[[0.18043353 0.32167833]
 [0.1857404  0.31825622]
 [0.71642725 0.56464813]
 [0.27719543 0.39696475]
 [0.58552449 0.56464813]]

